fixes issues #18 #19
coding-blocks/dev-submit pull request #34
Opened 2017-07-03 10:50 UTC by tech4GT

Signed-off-by: tech4GT <varun.gupta1798@gmail.com>

2017-07-03 10:52 UTC, tech4GT commented
@championswimmer sir please go through the new structure of submissions table and its associations and provide your review

2017-07-03 16:55 UTC, championswimmer requested changes

2017-07-03 16:55 UTC, championswimmer commented on db/actions/submissions.js
> +function addSubmission(studentId, BatchAssnId, URL, done) {
variables start with small letter

2017-07-03 16:55 UTC, championswimmer commented on db/actions/submissions.js
> +            }).then(function (BatchAssignmentData) {
variables start with small letter

2017-07-03 16:55 UTC, championswimmer commented on db/actions/submissions.js
>      models.Submissions
variables start with small letter

2017-07-03 16:55 UTC, championswimmer commented on routes/api_v1/submissions.js
> +      req.body.BatchAssignmentId,
req arguments should also be with small

2017-07-03 16:55 UTC, championswimmer commented on routes/api_v1/submissions.js
> +      options.batch_assignmentId = req.query.BatchAssignment;
either use camelCase or underscore_case. not both

2017-07-03 17:06 UTC, tech4GT commented
@championswimmer sir done all the changes

2017-07-03 17:13 UTC, championswimmer requested changes

2017-07-03 17:13 UTC, championswimmer commented on db/models.js
> -    URL: Sequelize.STRING
dont use ALL CAPS keys in objects.

2017-07-03 17:13 UTC, championswimmer commented on routes/api_v1/submissions.js
> +      req.body.batch_assignmentId,
camel and underscore mixed

2017-07-03 17:13 UTC, championswimmer commented on routes/api_v1/submissions.js
> +      options.batch_assignmentId = req.query.batch_assignment;
camel underscore mixed

2017-07-03 17:26 UTC, tech4GT commented
@championswimmer worked out these ones as well

2017-07-06 18:52 UTC, championswimmer approved these changes

2017-07-06 18:52 UTC, merged